### ISSUE TITLE
border numbers slightly inaccurate

### ISSUE THREAD

**Issue by bferguson3** [jlbeard84/web-cross#1]
![image](https://user-images.githubusercontent.com/32964659/57881839-48474f00-77f0-11e9-8b0c-2a773d2d69cf.png)

    `private readonly sampleData = [
        0, 1, 1, 1, 1, 1, 1, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 1, 1, 1, 1, 0, 0,
        1, 0, 1, 0, 0, 0, 0, 1, 0,
        1, 0, 1, 0, 0, 1, 0, 1, 0,
        1, 0, 1, 1, 1, 0, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 1, 1, 1, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];`

**Comment by jlbeard84** [comment]
Fixed for now but display size for these numbers should be more dynamic in case there are a lot of them...
